<?php
require 'Computer.php';

class Laptop extends Computer
{
    public function run ()
    {
        parent::run(); // TODO: Change the autogenerated stub
        echo "I am laptop, I am running";
    }
}

$asus = new Laptop();
$asus->run();
?>